### PR TITLE
9.1 and 9.2 new pets added to map spawn points

### PR DESCRIPTION
**Pull request by mrtnkiss**
### Overview of this pull request

I've collected the possible spawn points for the pets added in 9.1 and 9.2 and this update has the coordinates stored in the format required for PetTracker and the coordinates are added to the Data.lua file.

### List of pets added from 9.1

note: wild pet coordinates are copied from WoWhead, and since they are very dense, some cleansing would be beneficial, possibly clustering the coordinates based on distance (possible enhancement). 

note 2: [Wild Corpsefly](https://www.wowhead.com/npc=179329/) is only found as secondary pet in Korthia/The Maw

| Battle Pet URL                                              | Source                   |
| ----------------------------------------------------------- | ------------------------ |
| [Animite Broodling](https://www.wowhead.com/npc=179131/)    | Korthia - Battle         |
| [Anxious Nibbler](https://www.wowhead.com/npc=179248/)      | Korthia - Battle         |
| [Devourling](https://www.wowhead.com/npc=179256/)           | Korthia - Battle         |
| [Young   Garnetgullet](https://www.wowhead.com/npc=179250/) | Korthia - Battle         |
| [Domestic Aunian](https://www.wowhead.com/npc=179253/)      | Korthia - Vendor         |
| [Curious Purrkin](https://www.wowhead.com/npc=179164/)      | Tazavesh - Battle        |
| [Damp Skrat](https://www.wowhead.com/npc=179167/)           | Tazavesh - Battle        |
| [Scavenging Skrat](https://www.wowhead.com/npc=179168/)     | Tazavesh - Battle        |
| [Silver Purrkin](https://www.wowhead.com/npc=179165/)       | Tazavesh - Battle        |
| [Gizmo](https://www.wowhead.com/npc=179166/)                | Tazavesh - Boss Drop     |
| [Rarity](https://www.wowhead.com/npc=179169/)               | Tazavesh - Secret Vendor |
| [Clinging Remains](https://www.wowhead.com/npc=179179/)     | The Maw - Battle         |
| [Deathroach](https://www.wowhead.com/npc=179226/)           | The Maw - Battle         |
| [Eye of Affliction](https://www.wowhead.com/npc=179229/)    | The Maw - Battle         |
| [Grip of Terror](https://www.wowhead.com/npc=179219/)       | The Maw - Battle         |
| [Lost Limb](https://www.wowhead.com/npc=179183/)            | The Maw - Battle         |
| [Scurrying Mawrat](https://www.wowhead.com/npc=179182/)     | The Maw - Battle         |
| [Vile Deathroach](https://www.wowhead.com/npc=179227/)      | The Maw - Battle         |
| [Golden Eye](https://www.wowhead.com/npc=179228/)           | The Maw - Drop           |
| [Grappling   Gauntlet](https://www.wowhead.com/npc=179220/) | The Maw - Drop           |
| [Amaranthine Stinger](https://www.wowhead.com/npc=179181/)  | The Maw - Tormentor Drop |

### List of pets added from 9.2

note: [Momma Vombata](https://ptr.wowhead.com/npc=183158/) I found once, possibly it has a shared spawn point with [Vombata Pup](https://ptr.wowhead.com/npc=183142/)

note 2: [Enraged Poultrid](https://ptr.wowhead.com/npc=183285/) and [Mawtouched   Geomental](https://ptr.wowhead.com/npc=183230/) are the pets which I did not encounter on the 9.2 PTR, they are possibly related to Cipher of the First ones research / some other quest/achievement.

| Battle Pet URL                                               | Source                 |
| ------------------------------------------------------------ | ---------------------- |
| [Ambystan Snapper](https://ptr.wowhead.com/npc=183277/)      | Zereth Mortis - Battle |
| [Aurelid Floater](https://ptr.wowhead.com/npc=183281/)       | Zereth Mortis - Battle |
| [Bloodsucker   Vespoid](https://ptr.wowhead.com/npc=182876/) | Zereth Mortis - Battle |
| [Bufonid Croaker](https://ptr.wowhead.com/npc=181362/)       | Zereth Mortis - Battle |
| [Emerald Scarabid](https://ptr.wowhead.com/npc=182691/)      | Zereth Mortis - Battle |
| [Green Viperid](https://ptr.wowhead.com/npc=182768/)         | Zereth Mortis - Battle |
| [King Viperid](https://ptr.wowhead.com/npc=182760/)          | Zereth Mortis - Battle |
| [Metallic Scarabid](https://ptr.wowhead.com/npc=182568/)     | Zereth Mortis - Battle |
| [Momma Vombata](https://ptr.wowhead.com/npc=183158/)         | Zereth Mortis - Battle |
| [Predatory Helicid](https://ptr.wowhead.com/npc=183292/)     | Zereth Mortis - Battle |
| [Proto Avian   Fledgling](https://ptr.wowhead.com/npc=182260/) | Zereth Mortis - Battle |
| [Red Viperid](https://ptr.wowhead.com/npc=182758/)           | Zereth Mortis - Battle |
| [Scarlet Proto   Avian](https://ptr.wowhead.com/npc=182294/) | Zereth Mortis - Battle |
| [Tarachnid Ambusher](https://ptr.wowhead.com/npc=182473/)    | Zereth Mortis - Battle |
| [Tarachnid Stalker](https://ptr.wowhead.com/npc=182437/)     | Zereth Mortis - Battle |
| [Timid Leporid](https://ptr.wowhead.com/npc=182234/)         | Zereth Mortis - Battle |
| [Venomous Bufonid](https://ptr.wowhead.com/npc=182019/)      | Zereth Mortis - Battle |
| [Vicious Leporid](https://ptr.wowhead.com/npc=182216/)       | Zereth Mortis - Battle |
| [Vombata Pup](https://ptr.wowhead.com/npc=183142/)           | Zereth Mortis - Battle |

### CODE REVIEW

**Comment by Mike160770** [comment]
> ### Overview of this pull request
> I've collected the possible spawn points for the pets added in 9.1 and 9.2 and this update has the coordinates stored in the format required for PetTracker and the coordinates are added to the Data.lua file.
> 
> ### List of pets added from 9.1
> note: wild pet coordinates are copied from WoWhead, and since they are very dense, some cleansing would be beneficial, possibly clustering the coordinates based on distance (possible enhancement).
> 
> note 2: [Wild Corpsefly](https://www.wowhead.com/npc=179329/) is only found as secondary pet in Korthia/The Maw
> 
> Battle Pet URL	Source
> [Animite Broodling](https://www.wowhead.com/npc=179131/)	Korthia - Battle
> [Anxious Nibbler](https://www.wowhead.com/npc=179248/)	Korthia - Battle
> [Devourling](https://www.wowhead.com/npc=179256/)	Korthia - Battle
> [Young Garnetgullet](https://www.wowhead.com/npc=179250/)	Korthia - Battle
> [Domestic Aunian](https://www.wowhead.com/npc=179253/)	Korthia - Vendor
> [Curious Purrkin](https://www.wowhead.com/npc=179164/)	Tazavesh - Battle
> [Damp Skrat](https://www.wowhead.com/npc=179167/)	Tazavesh - Battle
> [Scavenging Skrat](https://www.wowhead.com/npc=179168/)	Tazavesh - Battle
> [Silver Purrkin](https://www.wowhead.com/npc=179165/)	Tazavesh - Battle
> [Gizmo](https://www.wowhead.com/npc=179166/)	Tazavesh - Boss Drop
> [Rarity](https://www.wowhead.com/npc=179169/)	Tazavesh - Secret Vendor
> [Clinging Remains](https://www.wowhead.com/npc=179179/)	The Maw - Battle
> [Deathroach](https://www.wowhead.com/npc=179226/)	The Maw - Battle
> [Eye of Affliction](https://www.wowhead.com/npc=179229/)	The Maw - Battle
> [Grip of Terror](https://www.wowhead.com/npc=179219/)	The Maw - Battle
> [Lost Limb](https://www.wowhead.com/npc=179183/)	The Maw - Battle
> [Scurrying Mawrat](https://www.wowhead.com/npc=179182/)	The Maw - Battle
> [Vile Deathroach](https://www.wowhead.com/npc=179227/)	The Maw - Battle
> [Golden Eye](https://www.wowhead.com/npc=179228/)	The Maw - Drop
> [Grappling Gauntlet](https://www.wowhead.com/npc=179220/)	The Maw - Drop
> [Amaranthine Stinger](https://www.wowhead.com/npc=179181/)	The Maw - Tormentor Drop
> 
> 
> 
> 
> 
> 
> ### List of pets added from 9.2
> note: [Momma Vombata](https://ptr.wowhead.com/npc=183158/) I found once, possibly it has a shared spawn point with [Vombata Pup](https://ptr.wowhead.com/npc=183142/)
> 
> note 2: [Enraged Poultrid](https://ptr.wowhead.com/npc=183285/) and [Mawtouched Geomental](https://ptr.wowhead.com/npc=183230/) are the pets which I did not encounter on the 9.2 PTR, they are possibly related to Cipher of the First ones research / some other quest/achievement.
> 
> Battle Pet URL	Source
> [Ambystan Snapper](https://ptr.wowhead.com/npc=183277/)	Zereth Mortis - Battle
> [Aurelid Floater](https://ptr.wowhead.com/npc=183281/)	Zereth Mortis - Battle
> [Bloodsucker Vespoid](https://ptr.wowhead.com/npc=182876/)	Zereth Mortis - Battle
> [Bufonid Croaker](https://ptr.wowhead.com/npc=181362/)	Zereth Mortis - Battle
> [Emerald Scarabid](https://ptr.wowhead.com/npc=182691/)	Zereth Mortis - Battle
> [Green Viperid](https://ptr.wowhead.com/npc=182768/)	Zereth Mortis - Battle
> [King Viperid](https://ptr.wowhead.com/npc=182760/)	Zereth Mortis - Battle
> [Metallic Scarabid](https://ptr.wowhead.com/npc=182568/)	Zereth Mortis - Battle
> [Momma Vombata](https://ptr.wowhead.com/npc=183158/)	Zereth Mortis - Battle
> [Predatory Helicid](https://ptr.wowhead.com/npc=183292/)	Zereth Mortis - Battle
> [Proto Avian Fledgling](https://ptr.wowhead.com/npc=182260/)	Zereth Mortis - Battle
> [Red Viperid](https://ptr.wowhead.com/npc=182758/)	Zereth Mortis - Battle
> [Scarlet Proto Avian](https://ptr.wowhead.com/npc=182294/)	Zereth Mortis - Battle
> [Tarachnid Ambusher](https://ptr.wowhead.com/npc=182473/)	Zereth Mortis - Battle
> [Tarachnid Stalker](https://ptr.wowhead.com/npc=182437/)	Zereth Mortis - Battle
> [Timid Leporid](https://ptr.wowhead.com/npc=182234/)	Zereth Mortis - Battle
> [Venomous Bufonid](https://ptr.wowhead.com/npc=182019/)	Zereth Mortis - Battle
> [Vicious Leporid](https://ptr.wowhead.com/npc=182216/)	Zereth Mortis - Battle
> [Vombata Pup](https://ptr.wowhead.com/npc=183142/)	Zereth Mortis - Battle
> 
> 
> 

Does not work for me - I use the German client - could that be the reason?
Greetings

**Comment by Mike160770** [comment]
Could you please upload the complete file you changed? I think I am too dumb to get the add-on working by just copying the changes you made.
Thx in advance!

**Comment by mrtnkiss** [comment]
> Could you please upload the complete file you changed? I think I am too dumb to get the add-on working by just copying the changes you made. Thx in advance!

Hi Mike, the file can be found in the forked repository in the same directory layout. The link to the modified file is [https://raw.githubusercontent.com/mrtnkiss/PetTracker/map-update-9.1-9.2-pets/addons/main/api/Data.lua](url). You need to overwrite the current file with this newly downloaded file in your PetTracker/addons/main/api/ folder

**Comment by Mike160770** [comment]
> > Could you please upload the complete file you changed? I think I am too dumb to get the add-on working by just copying the changes you made. Thx in advance!
> 
> Hi Mike, the file can be found in the forked repository in the same directory layout. The link to the modified file is https://raw.githubusercontent.com/mrtnkiss/PetTracker/map-update-9.1-9.2-pets/addons/main/api/Data.lua. You need to overwrite the current file with this newly downloaded file in your PetTracker/addons/main/api/ folder

Thx... does this also work for German clients?

**Comment by mrtnkiss** [comment]
> 

I'm not aware of anything that would make the addon incompatible with other locales. I could only test, however, with the EU-English locale client (works on both PTR and Retail)

**Comment by mynian** [comment]
Enraged Poultrid requires you to find an Agitated Poultrid critter in the wild, target it, and do the /chicken emote to spawn.

Mawtouched Geothermal requires the buff from the Questionable Mawshroom from Korthia and then they can be seen around 62, 74 in ZM

**Comment by mrtnkiss** [comment]
> 

Awesome, thanks for the information! :) I'll add the spawnpoints once I get around to making them spawn

**Comment by mrtnkiss** [comment]
Thanks to the help from @mynian , the following pets were added as spawn points in a commit to this PR.

| Battle Pet URL                                               | Source                 |
| ------------------------------------------------------------ | ---------------------- |
| [Enraged Poultrid (1)](https://www.wowhead.com/npc=183285/)  | Zereth Mortis - Battle |
| [Mawtouched Geomental (2)](https://www.wowhead.com/npc=183230/) | Zereth Mortis - Battle |
| [Momma Vombata (3)](https://www.wowhead.com/npc=183158/)     | Zereth Mortis - Battle |

Notes:

1) Enraged Poultrid is spawned upon encountering [Agitated Poultrid](https://www.wowhead.com/item=187244/questionable-mawshrooms) and doing a /chicken emote on it. Spawn points are for the Agitated Poultrid. These are non-combat critters so adding the NPC id (187244) to SilverDragon / NPCScan is a good way to find them 
2) Mawtouched Geomental can only be seen while under the effect of [Questionable Mawshrooms](https://www.wowhead.com/item=187244/questionable-mawshrooms), these can be found in Korthia in [Invasive Mawshroom](https://www.wowhead.com/search?q=Invasive%20Mawshroom) containers.
3) Momma Vombata seems to only rarely spawn in place of normal Vombata Pups. The spawn points are collected from wowhead and added my finds as well.

**Comment by Mike160770** [comment]
> Thanks to the help from @mynian , the following pets were added as spawn points in a commit to this PR.
> 
> Battle Pet URL	Source
> [Enraged Poultrid (1)](https://www.wowhead.com/npc=183285/)	Zereth Mortis - Battle
> [Mawtouched Geomental (2)](https://www.wowhead.com/npc=183230/)	Zereth Mortis - Battle
> [Momma Vombata (3)](https://www.wowhead.com/npc=183158/)	Zereth Mortis - Battle
> Notes:
> 
> 1. Enraged Poultrid is spawned upon encountering [Agitated Poultrid](https://www.wowhead.com/item=187244/questionable-mawshrooms) and doing a /chicken emote on it. Spawn points are for the Agitated Poultrid. These are non-combat critters so adding the NPC id (187244) to SilverDragon / NPCScan is a good way to find them
> 2. Mawtouched Geomental can only be seen while under the effect of [Questionable Mawshrooms](https://www.wowhead.com/item=187244/questionable-mawshrooms), these can be found in Korthia in [Invasive Mawshroom](https://www.wowhead.com/search?q=Invasive%20Mawshroom) containers.
> 3. Momma Vombata seems to only rarely spawn in place of normal Vombata Pups. The spawn points are collected from wowhead and added my finds as well.

Is there a new file ready for download?

**Comment by mrtnkiss** [comment]
Hi Mike, if there is an update to the branch I'm committing to, the file is updated, and the [link ](https://raw.githubusercontent.com/mrtnkiss/PetTracker/map-update-9.1-9.2-pets/addons/main/api/Data.lua) will get updated to the most current one, so you can use this file (Don't forget to /reload).

**Pull request closed without merging**
